# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "The Lazy Outdoors"
description:	       "Porfolio of travel pictures"
author:              "Georgia Molldrem"

domain: "thelazyoutdoors.com"
url: "https://thelazyoutdoors.com"